sudo: required
dist: trusty
language: python
python:
    - 2.7
    - 3.4
    - 3.5

before_install:
    - sudo pip install pytest-cov

script:
    - py.test --cov=csirtg_smrt --cov-fail-under=45
    - pip install -r dev_requirements.txt
    - make bin
    - ./pyinstaller-build/dist/csirtg-smrt -V
    - sudo apt-get install build-essential virtualenvwrapper python-virtualenv devscripts debhelper cdbs
    - make deb


notifications:
    email:
        on_success: never
        on_failure: never
