sudo: required
dist: trusty
language: python
python:
    - 2.7
#    - 3.4

script:
    - sudo pip install pytest-cov
    - py.test --cov=csirtg_smrt --cov-fail-under=45


notifications:
    email:
        on_success: never
        on_failure: never
